-- 1. Create the `blog_posts` table for manual articles
CREATE TABLE IF NOT EXISTS public.blog_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  technology TEXT NOT NULL DEFAULT 'Divers',
  excerpt TEXT NOT NULL,
  date TEXT NOT NULL,
  source_name TEXT NOT NULL DEFAULT 'Blog',
  url TEXT NOT NULL DEFAULT '#',
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('published', 'draft')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Configure Row Level Security (RLS) for `blog_posts`
ALTER TABLE public.blog_posts ENABLE ROW LEVEL SECURITY;

-- 3. Create policies
-- Allow anyone to read PUBLISHED manual posts (this policy can be used by the public API)
CREATE POLICY "Allow public read access to published posts" ON public.blog_posts
  FOR SELECT USING (status = 'published');

-- Allow authenticated users (admin) full access
CREATE POLICY "Allow authenticated full access to blog_posts" ON public.blog_posts
  FOR ALL TO authenticated USING (true);

-- (If using anon key for admin actions, consider tightening these rules in production)
-- Example for development allowing all actions:
CREATE POLICY "Allow anon full access for development" ON public.blog_posts
  FOR ALL TO anon USING (true);
