-- Table pour stocker individuellement les articles de blog générés par l'IA
-- Ceci permet de conserver l'historique de tous les articles sans les effacer

CREATE TABLE IF NOT EXISTS public.blog_articles_cache (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url TEXT UNIQUE NOT NULL,               -- Unique pour éviter les doublons d'articles
  title TEXT NOT NULL,
  technology TEXT NOT NULL,
  excerpt TEXT NOT NULL,
  date TEXT NOT NULL,
  source_name TEXT NOT NULL,
  fetched_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index pour accélérer le filtrage par technologie
CREATE INDEX IF NOT EXISTS blog_articles_cache_tech_idx ON public.blog_articles_cache (technology);

-- Désactiver RLS pour lecture publique (données non sensibles)
ALTER TABLE public.blog_articles_cache ENABLE ROW LEVEL SECURITY;

-- Politique : lecture publique
CREATE POLICY "blog_articles_cache_public_read"
  ON public.blog_articles_cache FOR SELECT
  USING (true);

-- Politique : écriture par le service (serveur Node)
CREATE POLICY "blog_articles_cache_service_write"
  ON public.blog_articles_cache FOR ALL
  USING (true)
  WITH CHECK (true);
